spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb?useSSL=false&serverTimezone=UTC
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

meilisearch:
  url: http://localhost:7700
  apiKey: masterKey
tmdb:
  apiKey: YOUR_TMDB_API_KEY
